version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - '5433'
    ports:
      - '5433:5433'
    command: -p 5433

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-tester-app
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db